#!/usr/bin/env bash

# Generates go.md

set -e

echo "# smartcontractkit Go modules
## Main module
\`\`\`mermaid
flowchart LR
"
(cd ./relayer && go mod graph) | go run github.com/jmank88/modgraph@v0.1.1 -prefix github.com/smartcontractkit/
echo "\`\`\`"

echo "## All modules
\`\`\`mermaid
flowchart LR
"
go run github.com/jmank88/gomods@v0.1.6 graph | go run github.com/jmank88/modgraph@v0.1.1 -prefix github.com/smartcontractkit/
echo "\`\`\`"