// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	address "github.com/fbsobreira/gotron-sdk/pkg/address"
	mock "github.com/stretchr/testify/mock"

	relayer "github.com/smartcontractkit/chainlink-internal-integrations/tron/relayer"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// BaseClient provides a mock function with given fields:
func (_m *Reader) BaseClient() relayer.GrpcClient {
	ret := _m.Called()

	var r0 relayer.GrpcClient
	if rf, ok := ret.Get(0).(func() relayer.GrpcClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(relayer.GrpcClient)
		}
	}

	return r0
}

// CallContract provides a mock function with given fields: _a0, _a1, _a2
func (_m *Reader) CallContract(_a0 address.Address, _a1 string, _a2 []map[string]string) (map[string]interface{}, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(address.Address, string, []map[string]string) (map[string]interface{}, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(address.Address, string, []map[string]string) map[string]interface{}); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(address.Address, string, []map[string]string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventsFromBlock provides a mock function with given fields: _a0, eventName, blockNum
func (_m *Reader) GetEventsFromBlock(_a0 address.Address, eventName string, blockNum uint64) ([]map[string]interface{}, error) {
	ret := _m.Called(_a0, eventName, blockNum)

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(address.Address, string, uint64) ([]map[string]interface{}, error)); ok {
		return rf(_a0, eventName, blockNum)
	}
	if rf, ok := ret.Get(0).(func(address.Address, string, uint64) []map[string]interface{}); ok {
		r0 = rf(_a0, eventName, blockNum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(address.Address, string, uint64) error); ok {
		r1 = rf(_a0, eventName, blockNum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LatestBlockHeight provides a mock function with given fields:
func (_m *Reader) LatestBlockHeight() (uint64, error) {
	ret := _m.Called()

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewReader interface {
	mock.TestingT
	Cleanup(func())
}

// NewReader creates a new instance of Reader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReader(t mockConstructorTestingTNewReader) *Reader {
	mock := &Reader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
