name: Relayer

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  test:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.5

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run tests
      run: cd relayer && go test -v -count=1 -tags=integration ./...
